/*!
 * jquery.customSelect() - v0.5.1
 * http://adam.co/lab/jquery/customselect/
 * 2014-03-19
 *
 * Copyright 2013 Adam Coulombe
 * @license http://www.opensource.org/licenses/mit-license.html MIT License
 * @license http://www.gnu.org/licenses/gpl.html GPL2 License 
 */
(function($){'use strict';$.fn.extend({customSelect:function(options){if(typeof document.body.style.maxHeight==='undefined'){return this;}
var defaults={customClass:'customSelect',mapClass:true,mapStyle:true},options=$.extend(defaults,options),prefix=options.customClass,changed=function($select,customSelectSpan){var currentSelected=$select.find(':selected'),customSelectSpanInner=customSelectSpan.children(':first'),html=currentSelected.html()||'&nbsp;';customSelectSpanInner.html(html);if(currentSelected.attr('disabled')){customSelectSpan.addClass(getClass('DisabledOption'));}else{customSelectSpan.removeClass(getClass('DisabledOption'));}
setTimeout(function(){customSelectSpan.removeClass(getClass('Open'));$(document).off('mouseup.customSelect');},60);},getClass=function(suffix){return prefix+suffix;};return this.each(function(){var $select=$(this),customSelectInnerSpan=$('<span />').addClass(getClass('Inner')),customSelectSpan=$('<span />');$select.after(customSelectSpan.append(customSelectInnerSpan));customSelectSpan.addClass(prefix);if(options.mapClass){customSelectSpan.addClass($select.attr('class'));}
if(options.mapStyle){customSelectSpan.attr('style',$select.attr('style'));}
$select.addClass('hasCustomSelect').on('render.customSelect',function(){changed($select,customSelectSpan);$select.css('width','');var selectBoxWidth=parseInt($select.outerWidth(),10)-
(parseInt(customSelectSpan.outerWidth(),10)-
parseInt(customSelectSpan.width(),10));customSelectSpan.css({display:'inline-block'});var selectBoxHeight=customSelectSpan.outerHeight();if($select.attr('disabled')){customSelectSpan.addClass(getClass('Disabled'));}else{customSelectSpan.removeClass(getClass('Disabled'));}
customSelectInnerSpan.css({width:selectBoxWidth,display:'inline-block'});$select.css({'-webkit-appearance':'menulist-button',width:customSelectSpan.outerWidth(),position:'absolute',opacity:0,height:selectBoxHeight,fontSize:customSelectSpan.css('font-size')});}).on('change.customSelect',function(){customSelectSpan.addClass(getClass('Changed'));changed($select,customSelectSpan);}).on('keyup.customSelect',function(e){if(!customSelectSpan.hasClass(getClass('Open'))){$select.trigger('blur.customSelect');$select.trigger('focus.customSelect');}else{if(e.which==13||e.which==27){changed($select,customSelectSpan);}}}).on('mousedown.customSelect',function(){customSelectSpan.removeClass(getClass('Changed'));}).on('mouseup.customSelect',function(e){if(!customSelectSpan.hasClass(getClass('Open'))){if($('.'+getClass('Open')).not(customSelectSpan).length>0&&typeof InstallTrigger!=='undefined'){$select.trigger('focus.customSelect');}else{customSelectSpan.addClass(getClass('Open'));e.stopPropagation();$(document).one('mouseup.customSelect',function(e){if(e.target!=$select.get(0)&&$.inArray(e.target,$select.find('*').get())<0){$select.trigger('blur.customSelect');}else{changed($select,customSelectSpan);}});}}}).on('focus.customSelect',function(){customSelectSpan.removeClass(getClass('Changed')).addClass(getClass('Focus'));}).on('blur.customSelect',function(){customSelectSpan.removeClass(getClass('Focus')+' '+getClass('Open'));}).on('mouseenter.customSelect',function(){customSelectSpan.addClass(getClass('Hover'));}).on('mouseleave.customSelect',function(){customSelectSpan.removeClass(getClass('Hover'));}).trigger('render.customSelect');});}});})(jQuery);var $j=jQuery.noConflict();$j(document).on('ready',function(){"use strict";oceanwpCustomSelects();});function oceanwpCustomSelects(){"use strict"
$j(oceanwpLocalize.customSelects).customSelect({customClass:'theme-select'});}var $j=jQuery.noConflict();$j(document).on('ready',function(){"use strict";oceanwpOverlaySearch();});function oceanwpOverlaySearch(){"use strict"
if('overlay'!=oceanwpLocalize.menuSearchStyle){return;}
var $searchOverlayToggle=$j('a.search-overlay-toggle'),$searchOverlayClose=$j('a.search-overlay-close'),$searchOverlay=$j('#searchform-overlay');if($searchOverlayToggle.length){$searchOverlayToggle.on('click',function(e){e.preventDefault();$searchOverlay.addClass('active');$searchOverlay.fadeIn(200);setTimeout(function(){$j('html').css('overflow','hidden');},400);});}
$searchOverlayClose.on('click',function(e){e.preventDefault();$searchOverlay.removeClass('active');$searchOverlay.fadeOut(200);setTimeout(function(){$j('html').css('overflow','visible');},400);});$searchOverlayToggle.on('click',function(){$j('#searchform-overlay input').focus();});};
/*!
* FitVids 1.1
*
* Copyright 2013, Chris Coyier - http://css-tricks.com + Dave Rupert - http://daverupert.com
* Credit to Thierry Koblentz - http://www.alistapart.com/articles/creating-intrinsic-ratios-for-video/
* Released under the WTFPL license - http://sam.zoy.org/wtfpl/
*
*/
(function($){'use strict';$.fn.fitVids=function(options){var settings={customSelector:null,ignore:null};if(!document.getElementById('fit-vids-style')){var head=document.head||document.getElementsByTagName('head')[0];var css='.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}';var div=document.createElement("div");div.innerHTML='<p>x</p><style id="fit-vids-style">'+css+'</style>';head.appendChild(div.childNodes[1]);}
if(options){$.extend(settings,options);}
return this.each(function(){var selectors=['iframe[src*="player.vimeo.com"]','iframe[src*="youtube.com"]','iframe[src*="youtube-nocookie.com"]','iframe[src*="kickstarter.com"][src*="video.html"]','object','embed'];if(settings.customSelector){selectors.push(settings.customSelector);}
var ignoreList='.fitvidsignore';if(settings.ignore){ignoreList=ignoreList+', '+settings.ignore;}
var $allVideos=$(this).find(selectors.join(','));$allVideos=$allVideos.not('object object');$allVideos=$allVideos.not(ignoreList);$allVideos.each(function(){var $this=$(this);if($this.parents(ignoreList).length>0){return;}
if(this.tagName.toLowerCase()==='embed'&&$this.parent('object').length||$this.parent('.fluid-width-video-wrapper').length){return;}
if((!$this.css('height')&&!$this.css('width'))&&(isNaN($this.attr('height'))||isNaN($this.attr('width'))))
{$this.attr('height',9);$this.attr('width',16);}
var height=(this.tagName.toLowerCase()==='object'||($this.attr('height')&&!isNaN(parseInt($this.attr('height'),10))))?parseInt($this.attr('height'),10):$this.height(),width=!isNaN(parseInt($this.attr('width'),10))?parseInt($this.attr('width'),10):$this.width(),aspectRatio=height/width;if(!$this.attr('name')){var videoName='fitvid'+$.fn.fitVids._count;$this.attr('name',videoName);$.fn.fitVids._count++;}
$this.wrap('<div class="fluid-width-video-wrapper"></div>').parent('.fluid-width-video-wrapper').css('padding-top',(aspectRatio*100)+'%');$this.removeAttr('height').removeAttr('width');});});};$.fn.fitVids._count=0;})(window.jQuery||window.Zepto);var $j=jQuery.noConflict();$j(document).on('ready',function(){"use strict";oceanwpInitFitVids();});function oceanwpInitFitVids($context){"use strict"
$j('.responsive-video-wrap, .responsive-audio-wrap',$context).fitVids();}
/*!
 * Infinite Scroll PACKAGED v3.0.2
 * Automatically add next page
 *
 * Licensed GPLv3 for open source use
 * or Infinite Scroll Commercial License for commercial use
 *
 * https://infinite-scroll.com
 * Copyright 2017 Metafizzy
 */

(function(window,factory){if(typeof define=='function'&&define.amd){define('jquery-bridget/jquery-bridget',['jquery'],function(jQuery){return factory(window,jQuery);});}else if(typeof module=='object'&&module.exports){module.exports=factory(window,require('jquery'));}else{window.jQueryBridget=factory(window,window.jQuery);}}(window,function factory(window,jQuery){'use strict';var arraySlice=Array.prototype.slice;var console=window.console;var logError=typeof console=='undefined'?function(){}:function(message){console.error(message);};function jQueryBridget(namespace,PluginClass,$){$=$||jQuery||window.jQuery;if(!$){return;}
if(!PluginClass.prototype.option){PluginClass.prototype.option=function(opts){if(!$.isPlainObject(opts)){return;}
this.options=$.extend(true,this.options,opts);};}
$.fn[namespace]=function(arg0){if(typeof arg0=='string'){var args=arraySlice.call(arguments,1);return methodCall(this,arg0,args);}
plainCall(this,arg0);return this;};function methodCall($elems,methodName,args){var returnValue;var pluginMethodStr='$().'+namespace+'("'+methodName+'")';$elems.each(function(i,elem){var instance=$.data(elem,namespace);if(!instance){logError(namespace+' not initialized. Cannot call methods, i.e. '+
pluginMethodStr);return;}
var method=instance[methodName];if(!method||methodName.charAt(0)=='_'){logError(pluginMethodStr+' is not a valid method');return;}
var value=method.apply(instance,args);returnValue=returnValue===undefined?value:returnValue;});return returnValue!==undefined?returnValue:$elems;}
function plainCall($elems,options){$elems.each(function(i,elem){var instance=$.data(elem,namespace);if(instance){instance.option(options);instance._init();}else{instance=new PluginClass(elem,options);$.data(elem,namespace,instance);}});}
updateJQuery($);}
function updateJQuery($){if(!$||($&&$.bridget)){return;}
$.bridget=jQueryBridget;}
updateJQuery(jQuery||window.jQuery);return jQueryBridget;}));(function(global,factory){if(typeof define=='function'&&define.amd){define('ev-emitter/ev-emitter',factory);}else if(typeof module=='object'&&module.exports){module.exports=factory();}else{global.EvEmitter=factory();}}(typeof window!='undefined'?window:this,function(){function EvEmitter(){}
var proto=EvEmitter.prototype;proto.on=function(eventName,listener){if(!eventName||!listener){return;}
var events=this._events=this._events||{};var listeners=events[eventName]=events[eventName]||[];if(listeners.indexOf(listener)==-1){listeners.push(listener);}
return this;};proto.once=function(eventName,listener){if(!eventName||!listener){return;}
this.on(eventName,listener);var onceEvents=this._onceEvents=this._onceEvents||{};var onceListeners=onceEvents[eventName]=onceEvents[eventName]||{};onceListeners[listener]=true;return this;};proto.off=function(eventName,listener){var listeners=this._events&&this._events[eventName];if(!listeners||!listeners.length){return;}
var index=listeners.indexOf(listener);if(index!=-1){listeners.splice(index,1);}
return this;};proto.emitEvent=function(eventName,args){var listeners=this._events&&this._events[eventName];if(!listeners||!listeners.length){return;}
var i=0;var listener=listeners[i];args=args||[];var onceListeners=this._onceEvents&&this._onceEvents[eventName];while(listener){var isOnce=onceListeners&&onceListeners[listener];if(isOnce){this.off(eventName,listener);delete onceListeners[listener];}
listener.apply(this,args);i+=isOnce?0:1;listener=listeners[i];}
return this;};proto.allOff=proto.removeAllListeners=function(){delete this._events;delete this._onceEvents;};return EvEmitter;}));(function(window,factory){'use strict';if(typeof define=='function'&&define.amd){define('desandro-matches-selector/matches-selector',factory);}else if(typeof module=='object'&&module.exports){module.exports=factory();}else{window.matchesSelector=factory();}}(window,function factory(){'use strict';var matchesMethod=(function(){var ElemProto=window.Element.prototype;if(ElemProto.matches){return'matches';}
if(ElemProto.matchesSelector){return'matchesSelector';}
var prefixes=['webkit','moz','ms','o'];for(var i=0;i<prefixes.length;i++){var prefix=prefixes[i];var method=prefix+'MatchesSelector';if(ElemProto[method]){return method;}}})();return function matchesSelector(elem,selector){return elem[matchesMethod](selector);};}));(function(window,factory){if(typeof define=='function'&&define.amd){define('fizzy-ui-utils/utils',['desandro-matches-selector/matches-selector'],function(matchesSelector){return factory(window,matchesSelector);});}else if(typeof module=='object'&&module.exports){module.exports=factory(window,require('desandro-matches-selector'));}else{window.fizzyUIUtils=factory(window,window.matchesSelector);}}(window,function factory(window,matchesSelector){var utils={};utils.extend=function(a,b){for(var prop in b){a[prop]=b[prop];}
return a;};utils.modulo=function(num,div){return((num%div)+div)%div;};utils.makeArray=function(obj){var ary=[];if(Array.isArray(obj)){ary=obj;}else if(obj&&typeof obj=='object'&&typeof obj.length=='number'){for(var i=0;i<obj.length;i++){ary.push(obj[i]);}}else{ary.push(obj);}
return ary;};utils.removeFrom=function(ary,obj){var index=ary.indexOf(obj);if(index!=-1){ary.splice(index,1);}};utils.getParent=function(elem,selector){while(elem.parentNode&&elem!=document.body){elem=elem.parentNode;if(matchesSelector(elem,selector)){return elem;}}};utils.getQueryElement=function(elem){if(typeof elem=='string'){return document.querySelector(elem);}
return elem;};utils.handleEvent=function(event){var method='on'+event.type;if(this[method]){this[method](event);}};utils.filterFindElements=function(elems,selector){elems=utils.makeArray(elems);var ffElems=[];elems.forEach(function(elem){if(!(elem instanceof HTMLElement)){return;}
if(!selector){ffElems.push(elem);return;}
if(matchesSelector(elem,selector)){ffElems.push(elem);}
var childElems=elem.querySelectorAll(selector);for(var i=0;i<childElems.length;i++){ffElems.push(childElems[i]);}});return ffElems;};utils.debounceMethod=function(_class,methodName,threshold){var method=_class.prototype[methodName];var timeoutName=methodName+'Timeout';_class.prototype[methodName]=function(){var timeout=this[timeoutName];if(timeout){clearTimeout(timeout);}
var args=arguments;var _this=this;this[timeoutName]=setTimeout(function(){method.apply(_this,args);delete _this[timeoutName];},threshold||100);};};utils.docReady=function(callback){var readyState=document.readyState;if(readyState=='complete'||readyState=='interactive'){setTimeout(callback);}else{document.addEventListener('DOMContentLoaded',callback);}};utils.toDashed=function(str){return str.replace(/(.)([A-Z])/g,function(match,$1,$2){return $1+'-'+$2;}).toLowerCase();};var console=window.console;utils.htmlInit=function(WidgetClass,namespace){utils.docReady(function(){var dashedNamespace=utils.toDashed(namespace);var dataAttr='data-'+dashedNamespace;var dataAttrElems=document.querySelectorAll('['+dataAttr+']');var jsDashElems=document.querySelectorAll('.js-'+dashedNamespace);var elems=utils.makeArray(dataAttrElems).concat(utils.makeArray(jsDashElems));var dataOptionsAttr=dataAttr+'-options';var jQuery=window.jQuery;elems.forEach(function(elem){var attr=elem.getAttribute(dataAttr)||elem.getAttribute(dataOptionsAttr);var options;try{options=attr&&JSON.parse(attr);}catch(error){if(console){console.error('Error parsing '+dataAttr+' on '+elem.className+': '+error);}
return;}
var instance=new WidgetClass(elem,options);if(jQuery){jQuery.data(elem,namespace,instance);}});});};return utils;}));(function(window,factory){if(typeof define=='function'&&define.amd){define('infinite-scroll/js/core',['ev-emitter/ev-emitter','fizzy-ui-utils/utils',],function(EvEmitter,utils){return factory(window,EvEmitter,utils);});}else if(typeof module=='object'&&module.exports){module.exports=factory(window,require('ev-emitter'),require('fizzy-ui-utils'));}else{window.InfiniteScroll=factory(window,window.EvEmitter,window.fizzyUIUtils);}}(window,function factory(window,EvEmitter,utils){var jQuery=window.jQuery;var instances={};function InfiniteScroll(element,options){var queryElem=utils.getQueryElement(element);if(!queryElem){console.error('Bad element for InfiniteScroll: '+(queryElem||element));return;}
element=queryElem;if(element.infiniteScrollGUID){var instance=instances[element.infiniteScrollGUID];instance.option(options);return instance;}
this.element=element;this.options=utils.extend({},InfiniteScroll.defaults);this.option(options);if(jQuery){this.$element=jQuery(this.element);}
this.create();}
InfiniteScroll.defaults={};InfiniteScroll.create={};InfiniteScroll.destroy={};var proto=InfiniteScroll.prototype;utils.extend(proto,EvEmitter.prototype);var GUID=0;proto.create=function(){var id=this.guid=++GUID;this.element.infiniteScrollGUID=id;instances[id]=this;this.pageIndex=1;this.loadCount=0;this.updateGetPath();if(!this.getPath){console.error('Disabling InfiniteScroll');return;}
this.updateGetAbsolutePath();this.log('initialized',[this.element.className]);this.callOnInit();for(var method in InfiniteScroll.create){InfiniteScroll.create[method].call(this);}};proto.option=function(opts){utils.extend(this.options,opts);};proto.callOnInit=function(){var onInit=this.options.onInit;if(onInit){onInit.call(this,this);}};proto.dispatchEvent=function(type,event,args){this.log(type,args);var emitArgs=event?[event].concat(args):args;this.emitEvent(type,emitArgs);if(!jQuery||!this.$element){return;}
type+='.infiniteScroll';var $event=type;if(event){var jQEvent=jQuery.Event(event);jQEvent.type=type;$event=jQEvent;}
this.$element.trigger($event,args);};var loggers={initialized:function(className){return'on '+className;},request:function(path){return'URL: '+path;},load:function(response,path){return(response.title||'')+'. URL: '+path;},error:function(error,path){return error+'. URL: '+path;},append:function(response,path,items){return items.length+' items. URL: '+path;},last:function(response,path){return'URL: '+path;},history:function(title,path){return'URL: '+path;},pageIndex:function(index,origin){return'current page determined to be: '+index+' from '+origin;},};proto.log=function(type,args){if(!this.options.debug){return;}
var message='[InfiniteScroll] '+type;var logger=loggers[type];if(logger){message+='. '+logger.apply(this,args);}
console.log(message);};proto.updateMeasurements=function(){this.windowHeight=window.innerHeight;var rect=this.element.getBoundingClientRect();this.top=rect.top+window.pageYOffset;};proto.updateScroller=function(){var elementScroll=this.options.elementScroll;if(!elementScroll){this.scroller=window;return;}
this.scroller=elementScroll===true?this.element:utils.getQueryElement(elementScroll);if(!this.scroller){throw'Unable to find elementScroll: '+elementScroll;}};proto.updateGetPath=function(){var optPath=this.options.path;if(!optPath){console.error('InfiniteScroll path option required. Set as: '+optPath);return;}
var type=typeof optPath;if(type=='function'){this.getPath=optPath;return;}
var templateMatch=type=='string'&&optPath.match('{{#}}');if(templateMatch){this.updateGetPathTemplate(optPath);return;}
this.updateGetPathSelector(optPath);};proto.updateGetPathTemplate=function(optPath){this.getPath=function(){var nextIndex=this.pageIndex+1;return optPath.replace('{{#}}',nextIndex);}.bind(this);var regexString=optPath.replace('{{#}}','(\\d\\d?\\d?)');var templateRe=new RegExp(regexString);var match=location.href.match(templateRe);if(match){this.pageIndex=parseInt(match[1],10);this.log('pageIndex',this.pageIndex,'template string');}};var pathRegexes=[/^(.*?\/?page\/?)(\d\d?\d?)(.*?$)/,/^(.*?\/?\?page=)(\d\d?\d?)(.*?$)/,/(.*?)(\d\d?\d?)(?!.*\d)(.*?$)/,];proto.updateGetPathSelector=function(optPath){var hrefElem=document.querySelector(optPath);if(!hrefElem){console.error('Bad InfiniteScroll path option. Next link not found: '+
optPath);return;}
var href=hrefElem.getAttribute('href');var pathParts,regex;for(var i=0;href&&i<pathRegexes.length;i++){regex=pathRegexes[i];var match=href.match(regex);if(match){pathParts=match.slice(1);break;}}
if(!pathParts){console.error('InfiniteScroll unable to parse next link href: '+href);return;}
this.isPathSelector=true;this.getPath=function(){var nextIndex=this.pageIndex+1;return pathParts[0]+nextIndex+pathParts[2];}.bind(this);this.pageIndex=parseInt(pathParts[1],10)-1;this.log('pageIndex',[this.pageIndex,'next link']);};proto.updateGetAbsolutePath=function(){var path=this.getPath();var isAbsolute=path.match(/^http/)||path.match(/^\//);if(isAbsolute){this.getAbsolutePath=this.getPath;return;}
var pathname=location.pathname;var directory=pathname.substring(0,pathname.lastIndexOf('/'));this.getAbsolutePath=function(){return directory+'/'+this.getPath();};};InfiniteScroll.create.hideNav=function(){var nav=utils.getQueryElement(this.options.hideNav);if(!nav){return;}
nav.style.display='none';this.nav=nav;};InfiniteScroll.destroy.hideNav=function(){if(this.nav){this.nav.style.display='';}};proto.destroy=function(){this.allOff();for(var method in InfiniteScroll.destroy){InfiniteScroll.destroy[method].call(this);}
delete this.element.infiniteScrollGUID;delete instances[this.guid];};InfiniteScroll.throttle=function(fn,threshold){threshold=threshold||200;var last,timeout;return function(){var now=+new Date();var args=arguments;var trigger=function(){last=now;fn.apply(this,args);}.bind(this);if(last&&now<last+threshold){clearTimeout(timeout);timeout=setTimeout(trigger,threshold);}else{trigger();}};};InfiniteScroll.data=function(elem){elem=utils.getQueryElement(elem);var id=elem&&elem.infiniteScrollGUID;return id&&instances[id];};InfiniteScroll.setJQuery=function($){jQuery=$;};utils.htmlInit(InfiniteScroll,'infinite-scroll');if(jQuery&&jQuery.bridget){jQuery.bridget('infiniteScroll',InfiniteScroll);}
return InfiniteScroll;}));(function(window,factory){if(typeof define=='function'&&define.amd){define('infinite-scroll/js/page-load',['./core',],function(InfiniteScroll){return factory(window,InfiniteScroll);});}else if(typeof module=='object'&&module.exports){module.exports=factory(window,require('./core'));}else{factory(window,window.InfiniteScroll);}}(window,function factory(window,InfiniteScroll){var proto=InfiniteScroll.prototype;InfiniteScroll.defaults.loadOnScroll=true;InfiniteScroll.defaults.checkLastPage=true;InfiniteScroll.defaults.responseType='document';InfiniteScroll.create.pageLoad=function(){this.canLoad=true;this.on('scrollThreshold',this.onScrollThresholdLoad);this.on('append',this.checkLastPage);if(this.options.outlayer){this.on('append',this.onAppendOutlayer);}};proto.onScrollThresholdLoad=function(){if(this.options.loadOnScroll){this.loadNextPage();}};proto.loadNextPage=function(){if(this.isLoading||!this.canLoad){return;}
var path=this.getAbsolutePath();this.isLoading=true;var onLoad=function(response){this.onPageLoad(response,path);}.bind(this);var onError=function(error){this.onPageError(error,path);}.bind(this);request(path,this.options.responseType,onLoad,onError);this.dispatchEvent('request',null,[path]);};proto.onPageLoad=function(response,path){if(!this.options.append){this.isLoading=false;}
this.pageIndex++;this.loadCount++;this.dispatchEvent('load',null,[response,path]);this.appendNextPage(response,path);return response;};proto.appendNextPage=function(response,path){var optAppend=this.options.append;var isDocument=this.options.responseType=='document';if(!isDocument||!optAppend){return;}
var items=response.querySelectorAll(optAppend);var fragment=getItemsFragment(items);var appendReady=function(){this.appendItems(items,fragment);this.isLoading=false;this.dispatchEvent('append',null,[response,path,items]);}.bind(this);if(this.options.outlayer){this.appendOutlayerItems(fragment,appendReady);}else{appendReady();}};proto.appendItems=function(items,fragment){if(!items||!items.length){return;}
fragment=fragment||getItemsFragment(items);refreshScripts(fragment);this.element.appendChild(fragment);};function getItemsFragment(items){var fragment=document.createDocumentFragment();for(var i=0;items&&i<items.length;i++){fragment.appendChild(items[i]);}
return fragment;}
function refreshScripts(fragment){var scripts=fragment.querySelectorAll('script');for(var i=0;i<scripts.length;i++){var script=scripts[i];var freshScript=document.createElement('script');copyAttributes(script,freshScript);script.parentNode.replaceChild(freshScript,script);}}
function copyAttributes(fromNode,toNode){var attrs=fromNode.attributes;for(var i=0;i<attrs.length;i++){var attr=attrs[i];toNode.setAttribute(attr.name,attr.value);}}
proto.appendOutlayerItems=function(fragment,appendReady){var imagesLoaded=InfiniteScroll.imagesLoaded||window.imagesLoaded;if(!imagesLoaded){console.error('[InfiniteScroll] imagesLoaded required for outlayer option');this.isLoading=false;return;}
imagesLoaded(fragment,appendReady);};proto.onAppendOutlayer=function(response,path,items){this.options.outlayer.appended(items);};proto.checkLastPage=function(response,path){var checkLastPage=this.options.checkLastPage;if(!checkLastPage){return;}
var pathOpt=this.options.path;if(typeof pathOpt=='function'){var nextPath=this.getPath();if(!nextPath){this.lastPageReached(response,path);return;}}
var selector;if(typeof checkLastPage=='string'){selector=checkLastPage;}else if(this.isPathSelector){selector=pathOpt;}
if(!selector||!response.querySelector){return;}
var nextElem=response.querySelector(selector);if(!nextElem){this.lastPageReached(response,path);}};proto.lastPageReached=function(response,path){this.canLoad=false;this.dispatchEvent('last',null,[response,path]);};proto.onPageError=function(error,path){this.isLoading=false;this.canLoad=false;this.dispatchEvent('error',null,[error,path]);return error;};InfiniteScroll.create.prefill=function(){if(!this.options.prefill){return;}
var append=this.options.append;if(!append){console.error('append option required for prefill. Set as :'+append);return;}
this.updateMeasurements();this.updateScroller();this.isPrefilling=true;this.on('append',this.prefill);this.once('error',this.stopPrefill);this.once('last',this.stopPrefill);this.prefill();};proto.prefill=function(){var distance=this.getPrefillDistance();this.isPrefilling=distance>=0;if(this.isPrefilling){this.log('prefill');this.loadNextPage();}else{this.stopPrefill();}};proto.getPrefillDistance=function(){if(this.options.elementScroll){return this.scroller.clientHeight-this.scroller.scrollHeight;}
return this.windowHeight-this.element.clientHeight;};proto.stopPrefill=function(){console.log('stopping prefill');this.off('append',this.prefill);};function request(url,responseType,onLoad,onError){var req=new XMLHttpRequest();req.open('GET',url,true);req.responseType=responseType||'';req.setRequestHeader('X-Requested-With','XMLHttpRequest');req.onload=function(){if(req.status==200){onLoad(req.response);}else{var error=new Error(req.statusText);onError(error);}};req.onerror=function(){var error=new Error('Network error requesting '+url);onError(error);};req.send();}
return InfiniteScroll;}));(function(window,factory){if(typeof define=='function'&&define.amd){define('infinite-scroll/js/scroll-watch',['./core','fizzy-ui-utils/utils',],function(InfiniteScroll,utils){return factory(window,InfiniteScroll,utils);});}else if(typeof module=='object'&&module.exports){module.exports=factory(window,require('./core'),require('fizzy-ui-utils'));}else{factory(window,window.InfiniteScroll,window.fizzyUIUtils);}}(window,function factory(window,InfiniteScroll,utils){var proto=InfiniteScroll.prototype;InfiniteScroll.defaults.scrollThreshold=400;InfiniteScroll.create.scrollWatch=function(){this.pageScrollHandler=this.onPageScroll.bind(this);this.resizeHandler=this.onResize.bind(this);var scrollThreshold=this.options.scrollThreshold;var isEnable=scrollThreshold||scrollThreshold===0;if(isEnable){this.enableScrollWatch();}};InfiniteScroll.destroy.scrollWatch=function(){this.disableScrollWatch();};proto.enableScrollWatch=function(){if(this.isScrollWatching){return;}
this.isScrollWatching=true;this.updateMeasurements();this.updateScroller();this.on('last',this.disableScrollWatch);this.bindScrollWatchEvents(true);};proto.disableScrollWatch=function(){if(!this.isScrollWatching){return;}
this.bindScrollWatchEvents(false);delete this.isScrollWatching;};proto.bindScrollWatchEvents=function(isBind){var addRemove=isBind?'addEventListener':'removeEventListener';this.scroller[addRemove]('scroll',this.pageScrollHandler);window[addRemove]('resize',this.resizeHandler);};proto.onPageScroll=InfiniteScroll.throttle(function(){var distance=this.getBottomDistance();if(distance<=this.options.scrollThreshold){this.dispatchEvent('scrollThreshold');}});proto.getBottomDistance=function(){if(this.options.elementScroll){return this.getElementBottomDistance();}else{return this.getWindowBottomDistance();}};proto.getWindowBottomDistance=function(){var bottom=this.top+this.element.clientHeight;var scrollY=window.pageYOffset+this.windowHeight;return bottom-scrollY;};proto.getElementBottomDistance=function(){var bottom=this.scroller.scrollHeight;var scrollY=this.scroller.scrollTop+this.scroller.clientHeight;return bottom-scrollY;};proto.onResize=function(){this.updateMeasurements();};utils.debounceMethod(InfiniteScroll,'onResize',150);return InfiniteScroll;}));(function(window,factory){if(typeof define=='function'&&define.amd){define('infinite-scroll/js/history',['./core','fizzy-ui-utils/utils',],function(InfiniteScroll,utils){return factory(window,InfiniteScroll,utils);});}else if(typeof module=='object'&&module.exports){module.exports=factory(window,require('./core'),require('fizzy-ui-utils'));}else{factory(window,window.InfiniteScroll,window.fizzyUIUtils);}}(window,function factory(window,InfiniteScroll,utils){var proto=InfiniteScroll.prototype;InfiniteScroll.defaults.history='replace';var link=document.createElement('a');InfiniteScroll.create.history=function(){if(!this.options.history){return;}
link.href=this.getAbsolutePath();var linkOrigin=link.origin||link.protocol+'//'+link.host;var isSameOrigin=linkOrigin==location.origin;if(!isSameOrigin){console.error('[InfiniteScroll] cannot set history with different origin: '+
link.origin+' on '+location.origin+' . History behavior disabled.');return;}
if(this.options.append){this.createHistoryAppend();}else{this.createHistoryPageLoad();}};proto.createHistoryAppend=function(){this.updateMeasurements();this.updateScroller();this.scrollPages=[{top:0,path:location.href,title:document.title,}];this.scrollPageIndex=0;this.scrollHistoryHandler=this.onScrollHistory.bind(this);this.unloadHandler=this.onUnload.bind(this);this.scroller.addEventListener('scroll',this.scrollHistoryHandler);this.on('append',this.onAppendHistory);this.bindHistoryAppendEvents(true);};proto.bindHistoryAppendEvents=function(isBind){var addRemove=isBind?'addEventListener':'removeEventListener';this.scroller[addRemove]('scroll',this.scrollHistoryHandler);window[addRemove]('unload',this.unloadHandler);};proto.createHistoryPageLoad=function(){this.on('load',this.onPageLoadHistory);};InfiniteScroll.destroy.history=proto.destroyHistory=function(){var isHistoryAppend=this.options.history&&this.options.append;if(isHistoryAppend){this.bindHistoryAppendEvents(false);}};proto.onAppendHistory=function(response,path,items){var firstItem=items[0];var elemScrollY=this.getElementScrollY(firstItem);link.href=path;this.scrollPages.push({top:elemScrollY,path:link.href,title:response.title,});};proto.getElementScrollY=function(elem){if(this.options.elementScroll){return this.getElementElementScrollY(elem);}else{return this.getElementWindowScrollY(elem);}};proto.getElementWindowScrollY=function(elem){var rect=elem.getBoundingClientRect();return rect.top+window.pageYOffset;};proto.getElementElementScrollY=function(elem){return elem.offsetTop-this.top;};proto.onScrollHistory=function(){var scrollViewY=this.getScrollViewY();var pageIndex,page;for(var i=0;i<this.scrollPages.length;i++){var scrollPage=this.scrollPages[i];if(scrollPage.top>=scrollViewY){break;}
pageIndex=i;page=scrollPage;}
if(pageIndex!=this.scrollPageIndex){this.scrollPageIndex=pageIndex;this.setHistory(page.title,page.path);}};utils.debounceMethod(InfiniteScroll,'onScrollHistory',150);proto.getScrollViewY=function(){if(this.options.elementScroll){return this.scroller.scrollTop+this.scroller.clientHeight/2;}else{return window.pageYOffset+this.windowHeight/2;}};proto.setHistory=function(title,path){var optHistory=this.options.history;var historyMethod=optHistory&&history[optHistory+'State'];if(!historyMethod){return;}
history[optHistory+'State'](null,title,path);if(this.options.historyTitle){document.title=title;}
this.dispatchEvent('history',null,[title,path]);};proto.onUnload=function(){var pageIndex=this.scrollPageIndex;if(pageIndex===0){return;}
var scrollPage=this.scrollPages[pageIndex];var scrollY=window.pageYOffset-scrollPage.top+this.top;this.destroyHistory();scrollTo(0,scrollY);};proto.onPageLoadHistory=function(response,path){this.setHistory(response.title,path);};return InfiniteScroll;}));(function(window,factory){if(typeof define=='function'&&define.amd){define('infinite-scroll/js/button',['./core','fizzy-ui-utils/utils',],function(InfiniteScroll,utils){return factory(window,InfiniteScroll,utils);});}else if(typeof module=='object'&&module.exports){module.exports=factory(window,require('./core'),require('fizzy-ui-utils'));}else{factory(window,window.InfiniteScroll,window.fizzyUIUtils);}}(window,function factory(window,InfiniteScroll,utils){InfiniteScroll.create.button=function(){var buttonElem=utils.getQueryElement(this.options.button);if(buttonElem){this.button=new InfiniteScrollButton(buttonElem,this);return;}};InfiniteScroll.destroy.button=function(){if(this.button){this.button.destroy();}};function InfiniteScrollButton(element,infScroll){this.element=element;this.infScroll=infScroll;this.clickHandler=this.onClick.bind(this);this.element.addEventListener('click',this.clickHandler);infScroll.on('request',this.disable.bind(this));infScroll.on('load',this.enable.bind(this));infScroll.on('error',this.hide.bind(this));infScroll.on('last',this.hide.bind(this));}
InfiniteScrollButton.prototype.onClick=function(event){event.preventDefault();this.infScroll.loadNextPage();};InfiniteScrollButton.prototype.enable=function(){this.element.removeAttribute('disabled');};InfiniteScrollButton.prototype.disable=function(){this.element.disabled='disabled';};InfiniteScrollButton.prototype.hide=function(){this.element.style.display='none';};InfiniteScrollButton.prototype.destroy=function(){this.element.removeEventListener('click',this.clickHandler);};InfiniteScroll.Button=InfiniteScrollButton;return InfiniteScroll;}));(function(window,factory){if(typeof define=='function'&&define.amd){define('infinite-scroll/js/status',['./core','fizzy-ui-utils/utils',],function(InfiniteScroll,utils){return factory(window,InfiniteScroll,utils);});}else if(typeof module=='object'&&module.exports){module.exports=factory(window,require('./core'),require('fizzy-ui-utils'));}else{factory(window,window.InfiniteScroll,window.fizzyUIUtils);}}(window,function factory(window,InfiniteScroll,utils){var proto=InfiniteScroll.prototype;InfiniteScroll.create.status=function(){var statusElem=utils.getQueryElement(this.options.status);if(!statusElem){return;}
this.statusElement=statusElem;this.statusEventElements={request:statusElem.querySelector('.infinite-scroll-request'),error:statusElem.querySelector('.infinite-scroll-error'),last:statusElem.querySelector('.infinite-scroll-last'),};this.on('request',this.showRequestStatus);this.on('error',this.showErrorStatus);this.on('last',this.showLastStatus);this.bindHideStatus('on');};proto.bindHideStatus=function(bindMethod){var hideEvent=this.options.append?'append':'load';this[bindMethod](hideEvent,this.hideAllStatus);};proto.showRequestStatus=function(){this.showStatus('request');};proto.showErrorStatus=function(){this.showStatus('error');};proto.showLastStatus=function(){this.showStatus('last');this.bindHideStatus('off');};proto.showStatus=function(eventName){show(this.statusElement);this.hideStatusEventElements();var eventElem=this.statusEventElements[eventName];show(eventElem);};proto.hideAllStatus=function(){hide(this.statusElement);this.hideStatusEventElements();};proto.hideStatusEventElements=function(){for(var type in this.statusEventElements){var eventElem=this.statusEventElements[type];hide(eventElem);}};function hide(elem){setDisplay(elem,'none');}
function show(elem){setDisplay(elem,'block');}
function setDisplay(elem,value){if(elem){elem.style.display=value;}}
return InfiniteScroll;}));
/*!
 * Infinite Scroll v3.0.2
 * Automatically add next page
 *
 * Licensed GPLv3 for open source use
 * or Infinite Scroll Commercial License for commercial use
 *
 * https://infinite-scroll.com
 * Copyright 2017 Metafizzy
 */
(function(window,factory){if(typeof define=='function'&&define.amd){define(['infinite-scroll/js/core','infinite-scroll/js/page-load','infinite-scroll/js/scroll-watch','infinite-scroll/js/history','infinite-scroll/js/button','infinite-scroll/js/status',],factory);}else if(typeof module=='object'&&module.exports){module.exports=factory(require('./core'),require('./page-load'),require('./scroll-watch'),require('./history'),require('./button'),require('./status'));}})(window,function factory(InfiniteScroll){return InfiniteScroll;});
/*!
 * imagesLoaded v4.1.3
 * JavaScript is all like "You images are done yet or what?"
 * MIT License
 */
(function(window,factory){'use strict';if(typeof define=='function'&&define.amd){define('imagesloaded/imagesloaded',['ev-emitter/ev-emitter'],function(EvEmitter){return factory(window,EvEmitter);});}else if(typeof module=='object'&&module.exports){module.exports=factory(window,require('ev-emitter'));}else{window.imagesLoaded=factory(window,window.EvEmitter);}})(typeof window!=='undefined'?window:this,function factory(window,EvEmitter){var $=window.jQuery;var console=window.console;function extend(a,b){for(var prop in b){a[prop]=b[prop];}
return a;}
function makeArray(obj){var ary=[];if(Array.isArray(obj)){ary=obj;}else if(typeof obj.length=='number'){for(var i=0;i<obj.length;i++){ary.push(obj[i]);}}else{ary.push(obj);}
return ary;}
function ImagesLoaded(elem,options,onAlways){if(!(this instanceof ImagesLoaded)){return new ImagesLoaded(elem,options,onAlways);}
if(typeof elem=='string'){elem=document.querySelectorAll(elem);}
this.elements=makeArray(elem);this.options=extend({},this.options);if(typeof options=='function'){onAlways=options;}else{extend(this.options,options);}
if(onAlways){this.on('always',onAlways);}
this.getImages();if($){this.jqDeferred=new $.Deferred();}
setTimeout(function(){this.check();}.bind(this));}
ImagesLoaded.prototype=Object.create(EvEmitter.prototype);ImagesLoaded.prototype.options={};ImagesLoaded.prototype.getImages=function(){this.images=[];this.elements.forEach(this.addElementImages,this);};ImagesLoaded.prototype.addElementImages=function(elem){if(elem.nodeName=='IMG'){this.addImage(elem);}
if(this.options.background===true){this.addElementBackgroundImages(elem);}
var nodeType=elem.nodeType;if(!nodeType||!elementNodeTypes[nodeType]){return;}
var childImgs=elem.querySelectorAll('img');for(var i=0;i<childImgs.length;i++){var img=childImgs[i];this.addImage(img);}
if(typeof this.options.background=='string'){var children=elem.querySelectorAll(this.options.background);for(i=0;i<children.length;i++){var child=children[i];this.addElementBackgroundImages(child);}}};var elementNodeTypes={1:true,9:true,11:true};ImagesLoaded.prototype.addElementBackgroundImages=function(elem){var style=getComputedStyle(elem);if(!style){return;}
var reURL=/url\((['"])?(.*?)\1\)/gi;var matches=reURL.exec(style.backgroundImage);while(matches!==null){var url=matches&&matches[2];if(url){this.addBackground(url,elem);}
matches=reURL.exec(style.backgroundImage);}};ImagesLoaded.prototype.addImage=function(img){var loadingImage=new LoadingImage(img);this.images.push(loadingImage);};ImagesLoaded.prototype.addBackground=function(url,elem){var background=new Background(url,elem);this.images.push(background);};ImagesLoaded.prototype.check=function(){var _this=this;this.progressedCount=0;this.hasAnyBroken=false;if(!this.images.length){this.complete();return;}
function onProgress(image,elem,message){setTimeout(function(){_this.progress(image,elem,message);});}
this.images.forEach(function(loadingImage){loadingImage.once('progress',onProgress);loadingImage.check();});};ImagesLoaded.prototype.progress=function(image,elem,message){this.progressedCount++;this.hasAnyBroken=this.hasAnyBroken||!image.isLoaded;this.emitEvent('progress',[this,image,elem]);if(this.jqDeferred&&this.jqDeferred.notify){this.jqDeferred.notify(this,image);}
if(this.progressedCount==this.images.length){this.complete();}
if(this.options.debug&&console){console.log('progress: '+message,image,elem);}};ImagesLoaded.prototype.complete=function(){var eventName=this.hasAnyBroken?'fail':'done';this.isComplete=true;this.emitEvent(eventName,[this]);this.emitEvent('always',[this]);if(this.jqDeferred){var jqMethod=this.hasAnyBroken?'reject':'resolve';this.jqDeferred[jqMethod](this);}};function LoadingImage(img){this.img=img;}
LoadingImage.prototype=Object.create(EvEmitter.prototype);LoadingImage.prototype.check=function(){var isComplete=this.getIsImageComplete();if(isComplete){this.confirm(this.img.naturalWidth!==0,'naturalWidth');return;}
this.proxyImage=new Image();this.proxyImage.addEventListener('load',this);this.proxyImage.addEventListener('error',this);this.img.addEventListener('load',this);this.img.addEventListener('error',this);this.proxyImage.src=this.img.src;};LoadingImage.prototype.getIsImageComplete=function(){return this.img.complete&&this.img.naturalWidth!==undefined;};LoadingImage.prototype.confirm=function(isLoaded,message){this.isLoaded=isLoaded;this.emitEvent('progress',[this,this.img,message]);};LoadingImage.prototype.handleEvent=function(event){var method='on'+event.type;if(this[method]){this[method](event);}};LoadingImage.prototype.onload=function(){this.confirm(true,'onload');this.unbindEvents();};LoadingImage.prototype.onerror=function(){this.confirm(false,'onerror');this.unbindEvents();};LoadingImage.prototype.unbindEvents=function(){this.proxyImage.removeEventListener('load',this);this.proxyImage.removeEventListener('error',this);this.img.removeEventListener('load',this);this.img.removeEventListener('error',this);};function Background(url,element){this.url=url;this.element=element;this.img=new Image();}
Background.prototype=Object.create(LoadingImage.prototype);Background.prototype.check=function(){this.img.addEventListener('load',this);this.img.addEventListener('error',this);this.img.src=this.url;var isComplete=this.getIsImageComplete();if(isComplete){this.confirm(this.img.naturalWidth!==0,'naturalWidth');this.unbindEvents();}};Background.prototype.unbindEvents=function(){this.img.removeEventListener('load',this);this.img.removeEventListener('error',this);};Background.prototype.confirm=function(isLoaded,message){this.isLoaded=isLoaded;this.emitEvent('progress',[this,this.element,message]);};ImagesLoaded.makeJQueryPlugin=function(jQuery){jQuery=jQuery||window.jQuery;if(!jQuery){return;}
$=jQuery;$.fn.imagesLoaded=function(options,callback){var instance=new ImagesLoaded(this,options,callback);return instance.jqDeferred.promise($(this));};};ImagesLoaded.makeJQueryPlugin();return ImagesLoaded;});var $j=jQuery.noConflict(),$window=$j(window);$window.on('load',function(){"use strict";if($j.fn.infiniteScroll!==undefined&&$j('div.infinite-scroll-nav').length){oceanwpInfiniteScrollInit();}});function oceanwpInfiniteScrollInit(){"use strict"
var $container=$j('.infinite-scroll-wrap');$container.infiniteScroll({path:'.older-posts a',append:'.item-entry',status:'.scroller-status',hideNav:'.infinite-scroll-nav',history:false,});$container.on('load.infiniteScroll',function(event,response,path,items){var $items=$j(response).find('.item-entry');$items.imagesLoaded(function(){$items.animate({opacity:1});$items.find('img').each(function(index,img){img.outerHTML=img.outerHTML;});if($container.hasClass('blog-masonry-grid')){$container.isotope('appended',$items);$items.css('opacity',0);}
if(!$j('body').hasClass('no-carousel')){oceanwpInitCarousel($items);}
if(!$j('body').hasClass('no-lightbox')){oceanwpInitLightbox($items);}
if(!$j('body').hasClass('no-fitvids')){oceanwpInitFitVids($items);}
if(!$j('body').hasClass('no-matchheight')){$j('.blog-equal-heights .blog-entry-inner').matchHeight({property:'min-height'});}
if($j('.gallery-format').parent('.thumbnail')&&$j('.blog-masonry-grid').length){setTimeout(function(){$j('.blog-masonry-grid').isotope('layout');},600+1);}});});};(function(factory){'use strict';if(typeof define==='function'&&define.amd){define(['jquery'],factory);}else if(typeof module!=='undefined'&&module.exports){module.exports=factory(require('jquery'));}else{factory(jQuery);}})(function($){var _previousResizeWidth=-1,_updateTimeout=-1;var _parse=function(value){return parseFloat(value)||0;};var _rows=function(elements){var tolerance=1,$elements=$(elements),lastTop=null,rows=[];$elements.each(function(){var $that=$(this),top=$that.offset().top-_parse($that.css('margin-top')),lastRow=rows.length>0?rows[rows.length-1]:null;if(lastRow===null){rows.push($that);}else{if(Math.floor(Math.abs(lastTop-top))<=tolerance){rows[rows.length-1]=lastRow.add($that);}else{rows.push($that);}}
lastTop=top;});return rows;};var _parseOptions=function(options){var opts={byRow:true,property:'height',target:null,remove:false};if(typeof options==='object'){return $.extend(opts,options);}
if(typeof options==='boolean'){opts.byRow=options;}else if(options==='remove'){opts.remove=true;}
return opts;};var matchHeight=$.fn.matchHeight=function(options){var opts=_parseOptions(options);if(opts.remove){var that=this;this.css(opts.property,'');$.each(matchHeight._groups,function(key,group){group.elements=group.elements.not(that);});return this;}
if(this.length<=1&&!opts.target){return this;}
matchHeight._groups.push({elements:this,options:opts});matchHeight._apply(this,opts);return this;};matchHeight.version='0.7.2';matchHeight._groups=[];matchHeight._throttle=80;matchHeight._maintainScroll=false;matchHeight._beforeUpdate=null;matchHeight._afterUpdate=null;matchHeight._rows=_rows;matchHeight._parse=_parse;matchHeight._parseOptions=_parseOptions;matchHeight._apply=function(elements,options){var opts=_parseOptions(options),$elements=$(elements),rows=[$elements];var scrollTop=$(window).scrollTop(),htmlHeight=$('html').outerHeight(true);var $hiddenParents=$elements.parents().filter(':hidden');$hiddenParents.each(function(){var $that=$(this);$that.data('style-cache',$that.attr('style'));});$hiddenParents.css('display','block');if(opts.byRow&&!opts.target){$elements.each(function(){var $that=$(this),display=$that.css('display');if(display!=='inline-block'&&display!=='flex'&&display!=='inline-flex'){display='block';}
$that.data('style-cache',$that.attr('style'));$that.css({'display':display,'padding-top':'0','padding-bottom':'0','margin-top':'0','margin-bottom':'0','border-top-width':'0','border-bottom-width':'0','height':'100px','overflow':'hidden'});});rows=_rows($elements);$elements.each(function(){var $that=$(this);$that.attr('style',$that.data('style-cache')||'');});}
$.each(rows,function(key,row){var $row=$(row),targetHeight=0;if(!opts.target){if(opts.byRow&&$row.length<=1){$row.css(opts.property,'');return;}
$row.each(function(){var $that=$(this),style=$that.attr('style'),display=$that.css('display');if(display!=='inline-block'&&display!=='flex'&&display!=='inline-flex'){display='block';}
var css={'display':display};css[opts.property]='';$that.css(css);if($that.outerHeight(false)>targetHeight){targetHeight=$that.outerHeight(false);}
if(style){$that.attr('style',style);}else{$that.css('display','');}});}else{targetHeight=opts.target.outerHeight(false);}
$row.each(function(){var $that=$(this),verticalPadding=0;if(opts.target&&$that.is(opts.target)){return;}
if($that.css('box-sizing')!=='border-box'){verticalPadding+=_parse($that.css('border-top-width'))+_parse($that.css('border-bottom-width'));verticalPadding+=_parse($that.css('padding-top'))+_parse($that.css('padding-bottom'));}
$that.css(opts.property,(targetHeight-verticalPadding)+'px');});});$hiddenParents.each(function(){var $that=$(this);$that.attr('style',$that.data('style-cache')||null);});if(matchHeight._maintainScroll){$(window).scrollTop((scrollTop/htmlHeight)*$('html').outerHeight(true));}
return this;};matchHeight._applyDataApi=function(){var groups={};$('[data-match-height], [data-mh]').each(function(){var $this=$(this),groupId=$this.attr('data-mh')||$this.attr('data-match-height');if(groupId in groups){groups[groupId]=groups[groupId].add($this);}else{groups[groupId]=$this;}});$.each(groups,function(){this.matchHeight(true);});};var _update=function(event){if(matchHeight._beforeUpdate){matchHeight._beforeUpdate(event,matchHeight._groups);}
$.each(matchHeight._groups,function(){matchHeight._apply(this.elements,this.options);});if(matchHeight._afterUpdate){matchHeight._afterUpdate(event,matchHeight._groups);}};matchHeight._update=function(throttle,event){if(event&&event.type==='resize'){var windowWidth=$(window).width();if(windowWidth===_previousResizeWidth){return;}
_previousResizeWidth=windowWidth;}
if(!throttle){_update(event);}else if(_updateTimeout===-1){_updateTimeout=setTimeout(function(){_update(event);_updateTimeout=-1;},matchHeight._throttle);}};$(matchHeight._applyDataApi);var on=$.fn.on?'on':'bind';$(window)[on]('load',function(event){matchHeight._update(false,event);});$(window)[on]('resize orientationchange',function(event){matchHeight._update(true,event);});});var $j=jQuery.noConflict();$j(document).on('ready',function(){"use strict";oceanwpInitMatchHeight();});function oceanwpInitMatchHeight(){"use strict"
$j('.match-height-grid .match-height-content').matchHeight({property:'min-height'});$j('.blog-equal-heights .blog-entry-inner').matchHeight({property:'min-height'});}var $j=jQuery.noConflict();$j(document).on('ready',function(){"use strict";oceanwpNavNoClick();});function oceanwpNavNoClick(){"use strict"
$j('li.nav-no-click > a').on('click',function(){return false;});}var $j=jQuery.noConflict(),$window=$j(window);$j(document).on('ready',function(){"use strict";oceanwpScrollEffect();});function oceanwpScrollEffect(){"use strict"
if(!$j('body').hasClass('single-product')&&!$j('body').hasClass('no-local-scroll')){$j('a.local[href*="#"]:not([href="#"]), .local a[href*="#"]:not([href="#"]), a.menu-link[href*="#"]:not([href="#"]), a.sidr-class-menu-link[href*="#"]:not([href="#"])').on('click',function(){if(!$j(this).hasClass('omw-open-modal')&&!$j(this).parent().hasClass('omw-open-modal')&&!$j(this).parent().parent().parent().hasClass('omw-open-modal')&&!$j(this).parent().hasClass('opl-link')){var $href=$j(this).attr('href'),$hrefHash=$href.substr($href.indexOf('#')).slice(1),$target=$j('#'+$hrefHash),$adminbarHeight=oceanwpGetAdminbarHeight(),$topbarHeight=oceanwpGetTopbarHeight(),$stickyHeaderHeight=oceanwpGetStickyHeaderHeight(),$offset=$adminbarHeight+$topbarHeight+$stickyHeaderHeight,$scrollPosition;if($target.length&&''!==$hrefHash){$scrollPosition=$target.offset().top-$offset;$j('html, body').stop().animate({scrollTop:Math.round($scrollPosition)},1000);return false;}}});}}
function oceanwpGetAdminbarHeight(){"use strict"
var $offset=0,$adminBar=$j('#wpadminbar');if($adminBar.length){$offset=$adminBar.outerHeight();}
return $offset;}
function oceanwpGetTopbarHeight(){"use strict"
var $offset=0,$stickyTopBar=$j('#top-bar-wrap');if($stickyTopBar.hasClass('top-bar-sticky')&&$stickyTopBar.length){$offset=$stickyTopBar.outerHeight();}
return $offset;}
function oceanwpGetStickyHeaderHeight(){"use strict"
var $offset=0,$stickyHeader=$j('#site-header');if(!$stickyHeader.length){return;}
if($stickyHeader.hasClass('fixed-scroll')){$offset=$stickyHeader.data('height');}
if($window.width()<=960&&!$stickyHeader.hasClass('has-sticky-mobile')){$offset=$offset;}
if($stickyHeader.hasClass('medium-header')){if($j('#site-header .bottom-header-wrap').hasClass('fixed-scroll')){$offset=$j('#site-header .bottom-header-wrap').outerHeight();}else{$offset=$j('.is-sticky #site-header-inner').outerHeight();}}
if($stickyHeader.hasClass('vertical-header')){$offset=$offset;}
return $offset;}var $j=jQuery.noConflict(),$window=$j(window);$j(document).on('ready',function(){"use strict";oceanwpScrollTop();});function oceanwpScrollTop(){"use strict"
var selectors={scrollTop:'#scroll-top',topLink:'a[href="#go-top"]',slashTopLink:'body.home a[href="/#go-top"]'}
$window.on('scroll',function(){if($j(this).scrollTop()>100){$j('#scroll-top').fadeIn();}else{$j('#scroll-top').fadeOut();}});$j.each(selectors,function(key,value){$j(value).on('click',function(e){e.preventDefault();$j('html, body').animate({scrollTop:0},400);$j(this).parent().removeClass('sfHover');});});}
/*! sidr - v2.2.1 - 2016-02-17
 * http://www.berriart.com/sidr/
 * Copyright (c) 2013-2016 Alberto Varela; Licensed MIT */

(function(){'use strict';var babelHelpers={};babelHelpers.classCallCheck=function(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}};babelHelpers.createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}
return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};}();babelHelpers;var sidrStatus={moving:false,opened:false};var helper={isUrl:function isUrl(str){var pattern=new RegExp('^(https?:\\/\\/)?'+'((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.?)+[a-z]{2,}|'+'((\\d{1,3}\\.){3}\\d{1,3}))'+'(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*'+'(\\?[;&a-z\\d%_.~+=-]*)?'+'(\\#[-a-z\\d_]*)?$','i');if(pattern.test(str)){return true;}else{return false;}},addPrefixes:function addPrefixes($element){this.addPrefix($element,'id');this.addPrefix($element,'class');$element.removeAttr('style');},addPrefix:function addPrefix($element,attribute){var toReplace=$element.attr(attribute);if(typeof toReplace==='string'&&toReplace!==''&&toReplace!=='sidr-inner'){$element.attr(attribute,toReplace.replace(/([A-Za-z0-9_.\-]+)/g,'sidr-'+attribute+'-$1'));}},transitions:function(){var body=document.body||document.documentElement,style=body.style,supported=false,property='transition';if(property in style){supported=true;}else{(function(){var prefixes=['moz','webkit','o','ms'],prefix=undefined,i=undefined;property=property.charAt(0).toUpperCase()+property.substr(1);supported=function(){for(i=0;i<prefixes.length;i++){prefix=prefixes[i];if(prefix+property in style){return true;}}
return false;}();property=supported?'-'+prefix.toLowerCase()+'-'+property.toLowerCase():null;})();}
return{supported:supported,property:property};}()};var $$2=jQuery;var bodyAnimationClass='sidr-animating';var openAction='open';var closeAction='close';var transitionEndEvent='webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend';var Menu=function(){function Menu(name){babelHelpers.classCallCheck(this,Menu);this.name=name;this.item=$$2('#'+name);this.openClass=name==='sidr'?'sidr-open':'sidr-open '+name+'-open';this.menuWidth=this.item.outerWidth(true);this.speed=this.item.data('speed');this.side=this.item.data('side');this.displace=this.item.data('displace');this.timing=this.item.data('timing');this.method=this.item.data('method');this.onOpenCallback=this.item.data('onOpen');this.onCloseCallback=this.item.data('onClose');this.onOpenEndCallback=this.item.data('onOpenEnd');this.onCloseEndCallback=this.item.data('onCloseEnd');this.body=$$2(this.item.data('body'));}
babelHelpers.createClass(Menu,[{key:'getAnimation',value:function getAnimation(action,element){var animation={},prop=this.side;if(action==='open'&&element==='body'){animation[prop]=this.menuWidth+'px';}else if(action==='close'&&element==='menu'){animation[prop]='-'+this.menuWidth+'px';}else{animation[prop]=0;}
return animation;}},{key:'prepareBody',value:function prepareBody(action){var prop=action==='open'?'hidden':'';if(this.body.is('body')){var $html=$$2('html'),scrollTop=$html.scrollTop();$html.css('overflow-x',prop).scrollTop(scrollTop);}}},{key:'openBody',value:function openBody(){if(this.displace){var transitions=helper.transitions,$body=this.body;if(transitions.supported){$body.css(transitions.property,this.side+' '+this.speed/1000+'s '+this.timing).css(this.side,0).css({width:$body.width(),position:'absolute'});$body.css(this.side,this.menuWidth+'px');}else{var bodyAnimation=this.getAnimation(openAction,'body');$body.css({width:$body.width(),position:'absolute'}).animate(bodyAnimation,{queue:false,duration:this.speed});}}}},{key:'onCloseBody',value:function onCloseBody(){var transitions=helper.transitions,resetStyles={width:'',position:'',right:'',left:''};if(transitions.supported){resetStyles[transitions.property]='';}
this.body.css(resetStyles).unbind(transitionEndEvent);}},{key:'closeBody',value:function closeBody(){var _this=this;if(this.displace){if(helper.transitions.supported){this.body.css(this.side,0).one(transitionEndEvent,function(){_this.onCloseBody();});}else{var bodyAnimation=this.getAnimation(closeAction,'body');this.body.animate(bodyAnimation,{queue:false,duration:this.speed,complete:function complete(){_this.onCloseBody();}});}}}},{key:'moveBody',value:function moveBody(action){if(action===openAction){this.openBody();}else{this.closeBody();}}},{key:'onOpenMenu',value:function onOpenMenu(callback){var name=this.name;sidrStatus.moving=false;sidrStatus.opened=name;this.item.unbind(transitionEndEvent);this.body.removeClass(bodyAnimationClass).addClass(this.openClass);this.onOpenEndCallback();if(typeof callback==='function'){callback(name);}}},{key:'openMenu',value:function openMenu(callback){var _this2=this;var $item=this.item;if(helper.transitions.supported){$item.css(this.side,0).one(transitionEndEvent,function(){_this2.onOpenMenu(callback);});}else{var menuAnimation=this.getAnimation(openAction,'menu');$item.css('display','block').animate(menuAnimation,{queue:false,duration:this.speed,complete:function complete(){_this2.onOpenMenu(callback);}});}}},{key:'onCloseMenu',value:function onCloseMenu(callback){this.item.css({left:'',right:''}).unbind(transitionEndEvent);$$2('html').css('overflow-x','');sidrStatus.moving=false;sidrStatus.opened=false;this.body.removeClass(bodyAnimationClass).removeClass(this.openClass);this.onCloseEndCallback();if(typeof callback==='function'){callback(name);}}},{key:'closeMenu',value:function closeMenu(callback){var _this3=this;var item=this.item;if(helper.transitions.supported){item.css(this.side,'').one(transitionEndEvent,function(){_this3.onCloseMenu(callback);});}else{var menuAnimation=this.getAnimation(closeAction,'menu');item.animate(menuAnimation,{queue:false,duration:this.speed,complete:function complete(){_this3.onCloseMenu();}});}}},{key:'moveMenu',value:function moveMenu(action,callback){this.body.addClass(bodyAnimationClass);if(action===openAction){this.openMenu(callback);}else{this.closeMenu(callback);}}},{key:'move',value:function move(action,callback){sidrStatus.moving=true;this.prepareBody(action);this.moveBody(action);this.moveMenu(action,callback);}},{key:'open',value:function open(callback){var _this4=this;if(sidrStatus.opened===this.name||sidrStatus.moving){return;}
if(sidrStatus.opened!==false){var alreadyOpenedMenu=new Menu(sidrStatus.opened);alreadyOpenedMenu.close(function(){_this4.open(callback);});return;}
this.move('open',callback);this.onOpenCallback();}},{key:'close',value:function close(callback){if(sidrStatus.opened!==this.name||sidrStatus.moving){return;}
this.move('close',callback);this.onCloseCallback();}},{key:'toggle',value:function toggle(callback){if(sidrStatus.opened===this.name){this.close(callback);}else{this.open(callback);}}}]);return Menu;}();var $$1=jQuery;function execute(action,name,callback){var sidr=new Menu(name);switch(action){case'open':sidr.open(callback);break;case'close':sidr.close(callback);break;case'toggle':sidr.toggle(callback);break;default:$$1.error('Method '+action+' does not exist on jQuery.sidr');break;}}
var i;var $=jQuery;var publicMethods=['open','close','toggle'];var methodName;var methods={};var getMethod=function getMethod(methodName){return function(name,callback){if(typeof name==='function'){callback=name;name='sidr';}else if(!name){name='sidr';}
execute(methodName,name,callback);};};for(i=0;i<publicMethods.length;i++){methodName=publicMethods[i];methods[methodName]=getMethod(methodName);}
function sidr(method){if(method==='status'){return sidrStatus;}else if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof method==='function'||typeof method==='string'||!method){return methods.toggle.apply(this,arguments);}else{$.error('Method '+method+' does not exist on jQuery.sidr');}}
var $$3=jQuery;function fillContent($sideMenu,settings){if(typeof settings.source==='function'){var newContent=settings.source(name);$sideMenu.html(newContent);}else if(typeof settings.source==='string'&&helper.isUrl(settings.source)){$$3.get(settings.source,function(data){$sideMenu.html(data);});}else if(typeof settings.source==='string'){var htmlContent='',selectors=settings.source.split(',');$$3.each(selectors,function(index,element){htmlContent+='<div class="sidr-inner">'+$$3(element).html()+'</div>';});if(settings.renaming){var $htmlContent=$$3('<div />').html(htmlContent);$htmlContent.find('*').each(function(index,element){var $element=$$3(element);helper.addPrefixes($element);});htmlContent=$htmlContent.html();}
$sideMenu.html(htmlContent);}else if(settings.source!==null){$$3.error('Invalid Sidr Source');}
return $sideMenu;}
function fnSidr(options){var transitions=helper.transitions,settings=$$3.extend({name:'sidr',speed:200,side:'left',source:null,renaming:true,body:'body',displace:true,timing:'ease',method:'toggle',bind:'touchstart click',onOpen:function onOpen(){},onClose:function onClose(){},onOpenEnd:function onOpenEnd(){},onCloseEnd:function onCloseEnd(){}},options),name=settings.name,$sideMenu=$$3('#'+name);if($sideMenu.length===0){$sideMenu=$$3('<div />').attr('id',name).appendTo($$3('body'));}
if(transitions.supported){$sideMenu.css(transitions.property,settings.side+' '+settings.speed/1000+'s '+settings.timing);}
$sideMenu.addClass('sidr').addClass(settings.side).data({speed:settings.speed,side:settings.side,body:settings.body,displace:settings.displace,timing:settings.timing,method:settings.method,onOpen:settings.onOpen,onClose:settings.onClose,onOpenEnd:settings.onOpenEnd,onCloseEnd:settings.onCloseEnd});$sideMenu=fillContent($sideMenu,settings);return this.each(function(){var $this=$$3(this),data=$this.data('sidr'),flag=false;if(!data){sidrStatus.moving=false;sidrStatus.opened=false;$this.data('sidr',name);$this.bind(settings.bind,function(event){event.preventDefault();if(!flag){flag=true;sidr(settings.method,name);setTimeout(function(){flag=false;},100);}});}});}
jQuery.sidr=sidr;jQuery.fn.sidr=fnSidr;}());var $j=jQuery.noConflict(),$window=$j(window);$j(document).on('ready',function(){"use strict";oceanwpMobileMenu();});function oceanwpMobileMenu(event){"use strict"
if(typeof oceanwpLocalize.sidrSource!=='undefined'&&$j('body').hasClass('sidebar-mobile')){$j('.mobile-menu').sidr({name:'sidr',source:oceanwpLocalize.sidrSource,side:oceanwpLocalize.sidrSide,displace:oceanwpLocalize.sidrDisplace,speed:300,renaming:true,bind:'click',onOpen:function onOpen(){$j('.mobile-menu > .hamburger').addClass('is-active');var $hasChildren=$j('.sidr-class-menu-item-has-children');$hasChildren.children('a').append('<span class="sidr-class-dropdown-toggle"></span>');var $sidrDropdownTarget=$j('.sidr-class-dropdown-toggle');if(oceanwpLocalize.sidrDropdownTarget=='link'){$sidrDropdownTarget=$j('li.sidr-class-menu-item-has-children > a');}
$sidrDropdownTarget.on('click',function(event){if(oceanwpLocalize.sidrDropdownTarget=='link'){var $toggleParentLi=$j(this).parent('li');}else{var $toggleParentLink=$j(this).parent('a'),$toggleParentLi=$toggleParentLink.parent('li');}
var $allParentLis=$toggleParentLi.parents('li'),$dropdown=$toggleParentLi.children('ul');if(!$toggleParentLi.hasClass('active')){$hasChildren.not($allParentLis).removeClass('active').children('ul').slideUp('fast');$toggleParentLi.addClass('active').children('ul').slideDown('fast');}else{$toggleParentLi.removeClass('active').children('ul').slideUp('fast');}
return false;});$j('body').append('<div class="oceanwp-sidr-overlay"></div>');$j('.oceanwp-sidr-overlay').fadeIn(300);$j('.oceanwp-sidr-overlay').on('click',function(){$j.sidr('close','sidr');return false;});$window.resize(function(){if($window.width()>=960){$j.sidr('close','sidr');$j('.mobile-menu > .hamburger').removeClass('is-active');}});},onClose:function onClose(){$j('.mobile-menu > .hamburger').removeClass('is-active');$j('.sidr-class-menu-item-has-children.active').removeClass('active').children('ul').hide();$j('.oceanwp-sidr-overlay').fadeOut(300,function(){$j(this).remove();});}});$j('#sidr [class*="sidr-class-fa"]').attr('class',function(i,c){c=c.replace('sidr-class-fa','fa');c=c.replace('sidr-class-fa-','fa-');return c;});$j('#sidr [class*="sidr-class-icon"]').attr('class',function(i,c){c=c.replace('sidr-class-icon-','icon-');return c;});$j('a.sidr-class-toggle-sidr-close').on('click',function(){$j.sidr('close','sidr');$j('.mobile-menu > .hamburger').removeClass('is-active');return false;});$j('.sidr-class-dropdown-menu a[href*="#"]:not([href="#"]), .sidr-class-menu-item > a[href*="#"]:not([href="#"])').on('click',function(){$j.sidr('close','sidr');$j('.mobile-menu > .hamburger').removeClass('is-active');});$j('li.sidr-class-nav-no-click > a').on('click',function(){return false;});}}var $j=jQuery.noConflict(),$window=$j(window);$j(document).on('ready',function(){"use strict";oceanwpDropDownMobile();});function oceanwpDropDownMobile(){"use strict"
if($j('body').hasClass('dropdown-mobile')){$j('.mobile-menu').on('click',function(){$j('#mobile-dropdown').slideToggle(500);$j(this).toggleClass('opened');$j('.mobile-menu > .hamburger').toggleClass('is-active');return false;});var oceanwpDropDownMobileClose=function(e){$j('#mobile-dropdown').slideUp(200);$j('.mobile-menu').removeClass('opened');$j('.mobile-menu > .hamburger').removeClass('is-active');}
var $hasChildren=$j('#mobile-dropdown .menu-item-has-children');$hasChildren.children('a').append('<span class="dropdown-toggle"></span>');var $dropdownTarget=$j('.dropdown-toggle');if(oceanwpLocalize.sidrDropdownTarget=='link'){$dropdownTarget=$j('#mobile-dropdown li.menu-item-has-children > a');}
$dropdownTarget.on('tap click',function(){if(oceanwpLocalize.sidrDropdownTarget=='link'){var $toggleParentLi=$j(this).parent('li');}else{var $toggleParentLink=$j(this).parent('a'),$toggleParentLi=$toggleParentLink.parent('li');}
var $allParentLis=$toggleParentLi.parents('li'),$dropdown=$toggleParentLi.children('ul');if(!$toggleParentLi.hasClass('active')){$hasChildren.not($allParentLis).removeClass('active').children('ul').slideUp('fast');$toggleParentLi.addClass('active').children('ul').slideDown('fast');}else{$toggleParentLi.removeClass('active').children('ul').slideUp('fast');}
return false;});$j(document).on('click',function(){oceanwpDropDownMobileClose();}).on('click','#mobile-dropdown',function(e){e.stopPropagation();});$window.resize(function(){if($window.width()>=960){oceanwpDropDownMobileClose();}});$j('#mobile-dropdown li a[href*="#"]:not([href="#"])').on('click',function(){oceanwpDropDownMobileClose();});}}